#allure.properties
allure.results.directory=test-outputs/Allure-Reports/allure-results
allure.report.directory=test-outputs/reports
allure.full.report.directory=test-outputs/full-report
allure.history.folder=history
allure.index.file=index.html
allure.report.prefix=AllureReport_
allure.report.extension=.html
allure.zip.base.url=https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/
allure.commandline.version=2.41.0
allure.extraction.directory=.m2/repository/allure



OpenAllureReportAfterExecution=false
